burning_airlines_server/config/routes.rb
Rails.application.routes.draw do
  resources :planes
  resources :flights
  resources :seats
  resources :reservations
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

burning_airlines_server/app/models/flight.rb
class Flight < ApplicationRecord
    belongs_to :plane
    has_many :reservations
end

burning_airlines_server/app/controllers/flights_controller.rb
class FlightsController < ApplicationController
before_action :set_flight, only: [:show, :edit, :update, :destroy]

  # GET /flights
  # GET /flights.json
  def index
    @flights = Flight.all
  end

  # GET /flights/1
  # GET /flights/1.json
  def show
  end

  # GET /flights/new
  def new
    @flights = Flight.new
  end

  # GET /flights/1/edit
  def edit
  end

  # POST /flights
  # POST /flights.json
  def create
    @flights = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1
  # PATCH/PUT /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.json
  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url, notice: 'Flight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flight_params
      params.require(:flight).permit(:name, :origin, :destination, :date, :time)
    end
end

burning_airlines_server/app/helpers/flights_helper.rb
module FlightsHelper
end

burning_airlines_server/app/views/flights/_form.html.erb
<%= form_with(model: flight, local: true) do |form| %>
  <% if flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
        <% flight.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

burning_airlines_server/app/views/flights/edit.html.erb
<h1>Editing Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

burning_airlines_server/app/views/flights/index.html.erb
<p id="notice"><%= notice %></p>

<h1>flights</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flights.each do |flight| %>
      <tr>
        <td><%= flight.name %></td>
        <td><%= link_to 'Show', flight %></td>
        <td><%= link_to 'Edit', edit_flight_path(flight) %></td>
        <td><%= link_to 'Destroy', flight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New flight', new_flight_path %>

burning_airlines_server/app/views/flights/new.html.erb
<h1>New flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Back', flights_path %>

burning_airlines_server/app/views/flights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @flight.name %>
</p>

<%= link_to 'Edit', edit_flight_path(@flight) %> |
<%= link_to 'Back', flights_path %>